[package]
name = "practice_samplecil"
version = "0.1.0"
authors = ["Kaito Akita <kaitokun07@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
